version: "3.9"

services:
  db:
    image: postgres:16
    container_name: rteca_postgres
    restart: always
    environment:
      POSTGRES_USER: rteca
      POSTGRES_PASSWORD: rteca
      POSTGRES_DB: rteca_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
